/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package hashcode2020

import org.junit.jupiter.api.Test
import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest  {

    @Test
    void testGreeting() {
        App app = new App()
        assertEquals("Hello world", app.greeting())
    }

}
